### ISSUE TITLE
v1.3 does not show any predictions

### ISSUE THREAD

**Issue by dariyooo** [dariyooo/DaKanji-mobile#15]
Hello!
I figured I send the bug report here since the captcha in github wasn't working on me.
After I updated my app to the lastest version just earlier, the grid and the box under the canvas does not display any characters anymore (as seen on the picture below)
I've tried to clear up cache and reinstall the app but it that doesn't seem to work.
For the details of my phone, I use an **Oppo A5s** with **Android 8.1.0** Please fix it soon. 
Thank you so much!

<img src="https://user-images.githubusercontent.com/51273483/132405154-366fa852-56f1-4f2d-9daf-7273eb5ca81d.jpg" width="250">

**Comment by CaptainDario** [comment]
Hello,

Thank you for the detailed bug report and the kind words. I will definitely look into whats going on.
Do I understand it correctly that the app was working for you in version 1.3 and suddenly stopped working? Or did it not work right from the beginning? I will try to look into it as soon as possible.

However until it works again you can download 1.2.x from github for a working version.

**Comment by CaptainDario** [comment]
Hello!No, the app didn't work from the beginning after the update. I'll be using the previous version for now then. Thank you so much for responding!

**Comment by CaptainDario** [comment]
Hello,
I started investigating this today.
My guess is that your phones tries to use the GPU as inference accelerator but somehow TF Lite does not work on PowerVR GPU's. I will add a setting which lets you choose the backend. Maybe this will fix your problem.

I opened an issue here: https://github.com/CaptainDario/DaKanji-Mobile/issues/15 to keep track of this. 

Would you be willing to spend some time trying beta versions so I can find a working solution?

Best regards,
Dario

**Comment by CaptainDario** [comment]
Fixed by merging #feature-select_inference_backend
